// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.DatabaseContext;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20231025214847_MoreDummyData")]
    partial class MoreDummyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.User.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5dd114bb-636c-4dc9-aa2d-d1be62608a87"),
                            Email = "test1@example.com",
                            MonthlyIncome = 1000m,
                            Name = "Test Name 1"
                        },
                        new
                        {
                            Id = new Guid("c84f7d42-a38c-4f2a-8218-f1ddca2ab6d3"),
                            Email = "test2@example.com",
                            MonthlyIncome = 2000m,
                            Name = "Test Name 2"
                        },
                        new
                        {
                            Id = new Guid("c4bd8356-d8e6-4236-b113-9503fef2a09c"),
                            Email = "test3@example.com",
                            MonthlyIncome = 3000m,
                            Name = "Test Name 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
