// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.DatabaseContext;

#nullable disable

namespace Repository.Migrations.Listing
{
    [DbContext(typeof(ListingContext))]
    [Migration("20231025214837_MoreDummyData")]
    partial class MoreDummyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Listing.PropertyListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PropertyListings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b2d4d98-fec9-4214-a63a-9a3e6697e1e4"),
                            Address = "123 Test Street",
                            City = "Test City",
                            ImageName = "default.png",
                            Price = 500000m,
                            Region = "Test Region"
                        },
                        new
                        {
                            Id = new Guid("76d7b3a2-8d3c-48e4-9390-e07c1d5ddddc"),
                            Address = "456 Sample Avenue",
                            City = "Sample Town",
                            ImageName = "sample.png",
                            Price = 750000m,
                            Region = "Sample Region"
                        },
                        new
                        {
                            Id = new Guid("82d9848d-9575-4710-9963-44dbcaab333a"),
                            Address = "789 Example Road",
                            City = "Exampleville",
                            ImageName = "example.png",
                            Price = 600000m,
                            Region = "Example State"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
